name: redouanstore
version: 1.0.0+1
publish_to: none
description: خضر وفواكه الرضوان.
environment: 
  sdk: '>=3.1.0-128.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  flutter_svg: ^2.0.5
  jovial_svg: ^1.1.14
  google_fonts: ^4.0.4
  flutter_portal: ^1.1.3
  font_awesome_flutter: ^10.4.0
  quds_ui_kit: ^0.0.7+10
  responsive: ^0.3.11+11
  flutter_animate: ^4.1.1+1
  responsive_framework: ^1.0.0
  responsive_ui: ^3.0.1
  navigation_drawer_menu: ^1.0.0-beta
  desktop_ui: ^0.0.5
  responsiveness: ^1.2.7
  bottom_bar_with_sheet: ^2.4.0
  snapping_sheet_2: ^3.1.5
  top_modal_sheet: ^2.0.1
  seo: ^0.0.4
  clay_containers: ^0.3.2
  flutter_lorem: ^2.0.0
  getwidget: ^3.1.1
  firebase_core: ^2.14.0
  firebase_database: ^10.2.4
  firebase: any
  neumorphic_button: ^0.0.1+2
  neumorphic_widget: ^0.0.1
  itwillrock_neumorphism: ^0.0.7
  flutter_components: ^1.0.5+5
  flutter_neumorphic: ^3.2.0
  measured_size: ^1.0.0
  auto_size_text: ^3.0.0
  visibility_detector: ^0.4.0+2
  skill_tree: ^0.0.1+3
  percent_indicator: ^4.2.3
  get_storage: ^2.1.1
  loading_indicator: any
  build_runner: ^2.4.5
  drift: ^2.9.0
  drift_dev: ^2.9.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.0
  riverpod: ^2.3.6
  image_picker_web: ^3.1.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  loading_animations: ^2.2.0
  web_hover_menu: ^0.0.3
  infinite_carousel: ^1.0.3
  carousel_slider: ^4.2.1
  responsive_builder: ^0.7.0
  searchbar_animation: ^0.0.4
  category_navigator: ^1.1.6
  mime_type: ^1.0.0
  accordion: ^2.5.1
  syncfusion_flutter_core: ^22.2.8
  syncfusion_flutter_datagrid: ^22.2.8
  form_validator: ^2.1.1
  file_picker: ^5.3.3
  firebase_storage_web: ^3.6.5
  firebase_storage: ^11.2.5
  url_params: ^1.6.0
  flutterfire_cli: ^0.2.7
  like_button: ^2.0.5
  uuid: ^3.0.7
  flutter_spinbox: ^0.13.1
  sendgrid_mailer: ^0.1.3
  flutter_mail_server: ^0.0.2
  mailer: ^6.0.1
  url_launcher: ^6.1.14
  whatsapp_unilink: ^2.1.0
  syncfusion_flutter_charts: ^22.2.12
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.2
  overlay_tooltip: ^0.2.3
  popover: ^0.2.8+2
  delayed_display: ^2.0.0
  marquee_widget:
  stepper_page_view: ^0.0.2
  intl: ^0.18.1
  bottom_sheet: ^4.0.0
  share_plus: ^7.1.0
  open_share_plus: ^1.2.0
  simple_ripple_animation: ^0.0.7
  crypto: ^3.0.3
  randomstring_dart: ^0.0.4
  search_page: ^2.3.0
  searchfield: ^0.8.7
  calendar_date_picker2: ^0.5.3
  date_picker_plus: ^1.1.4
  async_button: ^2.0.0-beta.1+2


  
 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
